// Auto-generated by sync-content.py
// Generated at: 2026-05-16T16:42:30.204446
// DO NOT EDIT MANUALLY - Edit YAML files in data/ instead

export const profile = {
  "name": "Aniekan Udo",
  "title": "Medical Student & AI Software Engineer",
  "tagline": "Data · AI · Fullstack · MLOps · Healthcare Technology",
  "bio": "Dual-degree candidate pursuing MB;BS (Medicine & Surgery) at \nUniversity of Ibadan and BSc Computer Science at University of the People. \nPublished researcher in medical AI (Glioma Segmentation, arxiv:2511.02928) with \nexperience across 6+ technical programs including SPARK Academy, McKinsey \nForward, and Aspire Institute. Building AI solutions that bridge healthcare \nand technology for Sub-Saharan Africa.\n",
  "photo": "/profile.jpg"
};

export const social = {
  "github": "Dr-Aniekan-Udo",
  "linkedin": "aniekan-etim-udo",
  "twitter": "anigram3",
  "email": "aniekanetimudo+reachout@gmail.com"
};

export const contact = {
  "description": "I'm open to full-time roles, contract work, collaborations, and consulting \nopportunities in software engineering, data, and AI.\n",
  "emailButton": "Send an Email",
  "githubButton": "View GitHub"
};

export const experience = [
  {
    "role": "Medical Image AI Engineer",
    "org": "SPARK Academy by CAMERA MRI Africa",
    "period": "Jan 2025 – Sep 2025",
    "description": "Led team to develop Glioma segmentation solution for low-resource settings. Published research on domain adaptive transformers for data-efficient medical image segmentation in Sub-Saharan MRI.",
    "tags": [
        "PyTorch",
        "Computer Vision",
        "Medical AI",
        "Research"
      ],
    "featured": true,
    "photo": "/experience/spark-academy.jpg",
    "photoAlt": "SPARK Academy team presentation",
    "priority": 1
  },
  {
    "role": "AI & Machine Learning Engineer Intern",
    "org": "Highland College of Technology",
    "period": "May 2024 – Nov 2024",
    "description": "Designed plant recognition AI model using computer vision for crop distribution analysis. Built and deployed models addressing economic growth and sustainability in Sub-Saharan Africa.",
    "tags": [
        "Python",
        "Image Processing",
        "3MTT Program"
      ],
    "featured": true,
    "photo": "/experience/highland-college.jpg",
    "photoAlt": "Highland College AI project",
    "priority": 2
  },
  {
    "role": "Board Member",
    "org": "FAMSA Headquarters (Federation of African Medical Students' Association)",
    "period": "Sep 2023 – Dec 2024",
    "description": "Served two tenures contributing to the planning and execution of FAMSA General Assemblies, coordinating outreach programs across African medical schools, and handling administrative duties for the federation. Developed strong leadership, organizational, and cross-cultural collaboration skills.",
    "tags": [
        "Leadership",
        "Healthcare Administration",
        "Community Outreach",
        "Event Planning"
      ],
    "featured": false,
    "photo": "/experience/famsa.jpg",
    "photoAlt": "FAMSA Headquarters",
    "priority": 3
  },
  {
    "role": "Data Scientist Intern",
    "org": "Skilharvest",
    "period": "Jan 2024 – May 2024",
    "description": "Led multi-functional data team to build loan defaulter, car price, and cancer prediction models. Designed handwritten text recognition using MNIST dataset.",
    "tags": [
        "Pandas",
        "Scikit-learn",
        "Deep Learning"
      ],
    "featured": false,
    "photo": "/experience/skilharvest.jpg",
    "photoAlt": "Skilharvest data team",
    "priority": 4
  },
  {
    "role": "Green Skill Trainee",
    "org": "INCO Academy (LinkedIn & Microsoft backed)",
    "period": "Mar 2024 – May 2024",
    "description": "Researched AI-powered healthcare solutions to reduce carbon emissions in health facilities. Proposed sustainable telemedicine chatbot to improve patient-doctor interaction.",
    "tags": [
        "Sustainability",
        "Healthcare AI",
        "Green Tech"
      ],
    "featured": false,
    "photo": "/experience/inco-academy.jpg",
    "photoAlt": "INCO Academy green skills program",
    "priority": 5
  },
  {
    "role": "Aspire Leadership Candidate",
    "org": "Aspire Institute (Harvard Business School faculty)",
    "period": "Sep 2024 – Nov 2024",
    "description": "Developed leadership, critical thinking, and problem-solving skills. Focused on driving social impact in low-income communities through technology.",
    "tags": [
        "Leadership",
        "Social Impact"
      ],
    "featured": false,
    "photo": "/experience/aspire-institute.jpg",
    "photoAlt": "Aspire Institute leadership program",
    "priority": 6
  },
  {
    "role": "McKinsey Forward Program Candidate",
    "org": "McKinsey & Company",
    "period": "May 2024 – Jul 2024",
    "description": "Learned hypothesis-driven problem solving, communication mastery, and interpersonal skills. Focused on driving economic growth in low-income countries.",
    "tags": [
        "Strategy",
        "Problem Solving"
      ],
    "featured": false,
    "photo": "/experience/mckinsey-forward.jpg",
    "photoAlt": "McKinsey Forward program",
    "priority": 7
  }
];

export const education = [
  {
    "degree": "Bachelor of Computer Science",
    "school": "University of the People",
    "period": "Sep 2025 – Present",
    "description": "Comprehensive computer science program covering software engineering, algorithms, data structures, systems programming, database management, web development, and AI/ML fundamentals. Building strong theoretical and practical foundations in computing alongside medical training.",
    "logo": "/education/uopeople-logo.png",
    "priority": 1
  },
  {
    "degree": "Bachelor of Medicine and Bachelor of Surgery (MB;BS)",
    "school": "University of Ibadan",
    "period": "Apr 2018 – Present",
    "description": "Rigorous medical training in clinical diagnosis, patient management, and evidence-based medicine. Developed systematic approach to disease management through history-taking, physical examination, investigations, and treatment planning. Actively participated in medical research, sports, and student leadership initiatives.",
    "logo": "/education/ui-logo.png",
    "priority": 2
  },
  {
    "degree": "AI Engineering Certificate",
    "school": "SPARK Academy",
    "period": "Jan 2025 – Aug 2025",
    "description": "Intensive medical AI program focused on deep learning, computer vision, and medical image segmentation. Completed research project on Glioma segmentation using domain adaptive transformers, leading to publication at WiML Workshop, NeurIPS 2025.",
    "logo": "/education/spark-academy-logo.png",
    "priority": 3
  },
  {
    "degree": "Software Engineering Program",
    "school": "ALX Africa",
    "period": "Jun 2022 – Dec 2023",
    "status": "Incomplete",
    "description": "Intensive full-stack software engineering program built on the 'Do Hard Things' philosophy. Mastered Linux, Bash, C Programming, Python, test-driven development, version control, and professional software engineering practices. Program discontinued by ALX, but skills gained remain foundational to all technical work.",
    "logo": "/education/alx-logo.png",
    "priority": 4
  },
  {
    "degree": "Google Data Analytics Certificate",
    "school": "Coursera",
    "period": "Feb 2024",
    "description": "Comprehensive data analytics training covering data collection, cleaning, analysis, and visualization. Proficient in SQL, R, spreadsheets, Tableau, and statistical analysis. Learned to transform raw data into actionable insights and compelling data stories for business decision-making.",
    "logo": "/education/coursera-logo.png",
    "priority": 5
  }
];

export const research = [
  {
    "repo": "Dr-Aniekan-Udo/glioma-segmentation-paper",
    "autoSync": true,
    "featured": true,
    "priority": 1
  }
];

export const skills = {
  "Healthcare AI": [
      "Python",
      "PyTorch",
      "Computer Vision",
      "Medical Imaging",
      "NLP",
      "Scikit-learn"
    ],
  "AI & Agents": [
      "LangGraph",
      "LangChain",
      "OpenAI",
      "MCP",
      "RAG",
      "Docling",
      "Chroma"
    ],
  "Fullstack": [
      "React",
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Streamlit",
      "Reflex"
    ],
  "Backend": [
      "Node.js",
      "Go",
      "Python",
      "PostgreSQL",
      "MongoDB",
      "REST APIs"
    ],
  "Data & MLOps": [
      "Pandas",
      "NumPy",
      "Jupyter",
      "Docker",
      "GitHub Actions",
      "AWS"
    ],
  "Core": [
      "Git",
      "Linux",
      "System Design",
      "Strategic Planning",
      "Team Management"
    ]
};
